// apps/worker/src/tasks/ingest_ktr_tone_dam.ts
//
// 国土交通省 関東地方整備局 利根川ダム統合管理事務所 — 9 国管理ダム hourly (JSON).
//
//   矢木沢 / 奈良俣 / 藤原 / 相俣 / 薗原 / 八ッ場 / 下久保 / 草木 (群馬)
//   渡良瀬貯水池 (栃木/群馬/埼玉/茨城)
//
// Source:
//   https://www.ktr.mlit.go.jp/tonedamu/teikyo/realtime2/json/E007010.json
//   JSON generated by the site's SPA; updated hourly.
//
// Format: UTF-8 JSON. damDataList array has one entry per dam.
//   officeCD+observationCD: dam identifier matching DAM_CONFIG keys.
//   dataList[0]: latest reading.
//     observationTime: "YYYY/MM/DD HH:MM:SS" (JST)
//     waterCapacity:   "N,NNN" (千m³)
//     waterRate:       "XX.X" (%)
//     inflow:          "XX.XX" (m³/s) or "休止中"
//     totalDischarge:  "XX.XX" (m³/s) or "休止中"
//   Aggregate entries (obsCD=8 "5ダム" and obsCD=29 "9ダム") are excluded.
//
// Note: 下久保ダム is also covered by the shimokubo adapter (priority 297,
// 10-minute resolution from a JWA telemetry feed). This adapter (priority 303)
// takes precedence at the hourly observation slots; the intra-hour shimokubo
// readings are unaffected.
//
// Priority 303. Cron hourly at :20.

import { sql } from '@dam/db/client';
import { upsertObservations } from '@dam/db/repo/observations';
import type { Task } from 'graphile-worker';

const DATA_URL =
  process.env.KTR_TONE_DAM_URL ??
  'https://www.ktr.mlit.go.jp/tonedamu/teikyo/realtime2/json/E007010.json';

const SOURCE_ID = 'ktr-tone-dam';

// --- dam configuration -------------------------------------------------------

interface DamCfg {
  officeCD: string;
  observationCD: string;
  name: string;
  prefCodes: string[];
}

// Aggregate entries (5ダム: obsCD=8, 9ダム: obsCD=29) are intentionally omitted.
const DAM_CONFIG: DamCfg[] = [
  { officeCD: '21289', observationCD: '1', name: '矢木沢ダム', prefCodes: ['10'] },
  { officeCD: '21289', observationCD: '2', name: '奈良俣ダム', prefCodes: ['10'] },
  { officeCD: '21289', observationCD: '3', name: '藤原ダム', prefCodes: ['10'] },
  { officeCD: '21289', observationCD: '4', name: '相俣ダム', prefCodes: ['10'] },
  { officeCD: '21289', observationCD: '5', name: '薗原ダム', prefCodes: ['10'] },
  { officeCD: '21289', observationCD: '27', name: '八ッ場ダム', prefCodes: ['10'] },
  { officeCD: '21289', observationCD: '6', name: '下久保ダム', prefCodes: ['10', '11'] },
  { officeCD: '21289', observationCD: '7', name: '草木ダム', prefCodes: ['10'] },
  {
    officeCD: '21259',
    observationCD: '1',
    name: '渡良瀬貯水池',
    prefCodes: ['09', '10', '11', '08'],
  },
];

/** Lookup key used to match damDataList entries to DAM_CONFIG. */
function damKey(officeCD: string, observationCD: string): string {
  return `${officeCD}/${observationCD}`;
}

const DAM_MAP = new Map<string, DamCfg>(
  DAM_CONFIG.map((d) => [damKey(d.officeCD, d.observationCD), d]),
);

// --- types -------------------------------------------------------------------

interface DataPoint {
  observationTime?: string;
  waterCapacity?: string;
  waterRate?: string;
  inflow?: string;
  totalDischarge?: string;
}

interface DamEntry {
  officeCD?: string;
  observationCD?: string;
  observationName?: string;
  dataList?: DataPoint[];
}

interface ToneDamJson {
  damDataList?: DamEntry[];
}

export interface ParsedRow {
  toneName: string;
  observedAt: Date;
  storageVolumeM3: number | null;
  storageRate: number | null;
  inflowM3s: number | null;
  outflowM3s: number | null;
}

// --- parsing -----------------------------------------------------------------

/** "YYYY/MM/DD HH:MM:SS" (JST) → UTC. Returns null for invalid input. */
export function parseToneTimestamp(ts: string): Date | null {
  const m = ts.match(/^(\d{4})\/(\d{2})\/(\d{2})\s+(\d{2}):(\d{2}):\d{2}$/);
  if (!m) return null;
  const d = new Date(
    Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]), Number(m[4]) - 9, Number(m[5]), 0),
  );
  return Number.isNaN(d.getTime()) ? null : d;
}

/**
 * Parse a value string that may contain commas ("43,918"), decimal points,
 * or non-numeric text ("休止中", "---"). Returns null for non-numeric values.
 */
function parseVal(s: string | undefined): number | null {
  if (!s) return null;
  const cleaned = s.replace(/,/g, '').trim();
  const n = Number(cleaned);
  return Number.isFinite(n) ? n : null;
}

export function parseToneDamJson(json: ToneDamJson): ParsedRow[] {
  const rows: ParsedRow[] = [];

  for (const entry of json.damDataList ?? []) {
    const key = damKey(entry.officeCD ?? '', entry.observationCD ?? '');
    const cfg = DAM_MAP.get(key);
    if (!cfg) continue; // aggregate or unknown entry

    const dp = entry.dataList?.[0];
    if (!dp?.observationTime) continue;

    const observedAt = parseToneTimestamp(dp.observationTime);
    if (!observedAt) continue;

    const capThousandM3 = parseVal(dp.waterCapacity);
    const storageVolumeM3 = capThousandM3 !== null ? capThousandM3 * 1000 : null;
    const ratePct = parseVal(dp.waterRate);
    const storageRate = ratePct !== null ? Math.max(0, Math.min(1, ratePct / 100)) : null;
    const inflowM3s = parseVal(dp.inflow);
    const outflowM3s = parseVal(dp.totalDischarge);

    if (
      storageVolumeM3 === null &&
      storageRate === null &&
      inflowM3s === null &&
      outflowM3s === null
    ) {
      continue;
    }

    rows.push({
      toneName: cfg.name,
      observedAt,
      storageVolumeM3,
      storageRate,
      inflowM3s,
      outflowM3s,
    });
  }

  return rows;
}

// --- DB helpers --------------------------------------------------------------

async function ensureSourcePriority(): Promise<void> {
  await sql`
    INSERT INTO source_priorities (source_id, priority, description, active)
    VALUES (${SOURCE_ID}, 303,
            '国土交通省 関東地方整備局 利根川ダム統合管理事務所 — 9 国管理ダム hourly JSON',
            true)
    ON CONFLICT (source_id) DO UPDATE
      SET priority    = EXCLUDED.priority,
          description = EXCLUDED.description,
          active      = EXCLUDED.active
  `;
}

function normalizeName(s: string): string {
  return s
    .replace(/[（(][^）)]*[）)]/g, '')
    .replace(/ダム$/, '')
    .replace(/貯水池$/, '')
    .trim();
}

interface DamMatch {
  toneName: string;
  damId: bigint;
}

async function matchMaster(rows: ParsedRow[], log: (s: string) => void): Promise<DamMatch[]> {
  const out: DamMatch[] = [];

  for (const r of rows) {
    const cfg = DAM_CONFIG.find((d) => d.name === r.toneName);
    if (!cfg) continue;

    const stem = normalizeName(r.toneName);
    if (!stem) continue;

    const masters = await sql<{ id: bigint; name: string }[]>`
      SELECT id, name FROM dams WHERE pref_code = ANY(${cfg.prefCodes}::text[]) ORDER BY id
    `;

    let best: { id: bigint; rank: number } | null = null;
    for (const m of masters) {
      const mStem = normalizeName(m.name);
      let rank: number;
      if (m.name === r.toneName) rank = 0;
      else if (mStem === stem) rank = 1;
      else if (m.name === `${stem}ダム`) rank = 2;
      else if (mStem.startsWith(stem)) rank = 3;
      else if (mStem.includes(stem)) rank = 4;
      else continue;
      if (!best || rank < best.rank || (rank === best.rank && m.id < best.id)) {
        best = { id: m.id, rank };
      }
    }

    if (!best) {
      log(`${SOURCE_ID}: no master match for "${r.toneName}" (prefs: ${cfg.prefCodes.join(',')})`);
      continue;
    }
    out.push({ toneName: r.toneName, damId: best.id });
  }

  return out;
}

// --- task --------------------------------------------------------------------

const task: Task = async (_payload, helpers) => {
  const log = (s: string): void => helpers.logger.info(s);
  await ensureSourcePriority();

  const r = await fetch(DATA_URL, {
    headers: {
      'user-agent':
        process.env.HTTP_USER_AGENT ??
        'DamDataPlatform/0.1 (+https://dam.teraren.com/legal/terms; contact: https://discord.gg/UbWqspWbAk)',
    },
    signal: AbortSignal.timeout(20_000),
  });

  if (r.status !== 200) {
    log(`${SOURCE_ID}: HTTP ${r.status}; aborting`);
    return;
  }

  // Strip UTF-8 BOM if present before JSON parsing
  const raw = await r.text();
  const json = JSON.parse(raw.replace(/^﻿/, '')) as ToneDamJson;
  const rows = parseToneDamJson(json);
  log(`${SOURCE_ID}: parsed ${rows.length} dam rows`);

  const matches = await matchMaster(rows, log);
  const damByName = new Map(matches.map((m) => [m.toneName, m.damId]));

  const inputs = [] as Parameters<typeof upsertObservations>[0];
  for (const p of rows) {
    const damId = damByName.get(p.toneName);
    if (!damId) continue;
    inputs.push({
      observedAt: p.observedAt,
      damId,
      sourceId: SOURCE_ID,
      storageVolumeM3: p.storageVolumeM3,
      storageRate: p.storageRate,
      inflowM3s: p.inflowM3s,
      outflowM3s: p.outflowM3s,
      waterLevelM: null,
      rainfallMm: null,
      rawSnapshotId: null,
      qualityFlag: 0,
    });
  }

  const written = await upsertObservations(inputs);
  log(`${SOURCE_ID} done: parsed=${rows.length} matched=${matches.length} written=${written}`);
};

export default task;
