/**
 * Join W01-seeded watershed rows (keyed by 水系名) to the 国土数値情報
 * 水系域コード codelist, decide each row's 河川法 kind, and render the
 * result as a SQL migration.
 */
import {
  kindFromWatershedCode,
  normalizeWatershedName,
  pickWatershedCandidate,
  type WatershedCandidate,
  type WatershedKind,
} from './watershed_kind.ts';

export interface WatershedRowInput {
  /** `watersheds.code` — the stable unique key (`W01-<水系名>`). */
  readonly code: string;
  readonly name: string;
  /** 2-digit pref codes of the dams attached to this watershed. */
  readonly prefCodes: readonly string[];
}

export interface ClassifiedWatershed {
  readonly code: string;
  readonly name: string;
  readonly ndiCode: string | null;
  readonly kind: WatershedKind;
  /** Every codelist entry sharing the (normalised) name — for review output. */
  readonly candidates: readonly WatershedCandidate[];
}

function indexCodelistByName(
  codelist: ReadonlyMap<string, string>,
): ReadonlyMap<string, readonly string[]> {
  const byName = new Map<string, string[]>();
  for (const [code, name] of codelist) {
    const key = normalizeWatershedName(name);
    byName.set(key, [...(byName.get(key) ?? []), code]);
  }
  return byName;
}

export function classifyWatersheds(
  rows: readonly WatershedRowInput[],
  codelist: ReadonlyMap<string, string>,
  sectionTypes: ReadonlyMap<string, ReadonlySet<string>>,
): ClassifiedWatershed[] {
  const byName = indexCodelistByName(codelist);
  return rows.map((row) => {
    const candidates = (byName.get(normalizeWatershedName(row.name)) ?? []).map((code) => ({
      code,
      kind: kindFromWatershedCode(code, sectionTypes.get(code)),
    }));
    const picked = pickWatershedCandidate(candidates, new Set(row.prefCodes));
    return {
      code: row.code,
      name: row.name,
      ndiCode: picked?.code ?? null,
      kind: picked?.kind ?? 'other',
      candidates,
    };
  });
}

const sqlLiteral = (v: string | null): string =>
  v == null ? 'NULL' : `'${v.replace(/'/g, "''")}'`;

export function renderWatershedKindMigration(
  rows: readonly ClassifiedWatershed[],
  note: string,
): string {
  const header = [
    `-- ${note}`,
    '-- Generated by apps/web/bin/classify_watershed_kind.ts — regenerate, do not hand-edit.',
    '',
    'ALTER TABLE watersheds ADD COLUMN IF NOT EXISTS ndi_code TEXT;',
    "COMMENT ON COLUMN watersheds.ndi_code IS '国土数値情報 水系域コード (河川コード上位 6 桁; W07_002 / W05_001 と同じ体系)。NULL = 水系名がコードリストと一致しなかった。';",
    '',
  ];
  if (rows.length === 0) return `${header.join('\n')}\n`;
  const values = rows
    .map((r) => `  (${sqlLiteral(r.code)}, ${sqlLiteral(r.ndiCode)}, ${sqlLiteral(r.kind)})`)
    .join(',\n');
  return [
    ...header,
    'UPDATE watersheds w',
    'SET kind = v.kind, ndi_code = v.ndi_code, updated_at = NOW()',
    'FROM (VALUES',
    values,
    ') AS v(code, ndi_code, kind)',
    'WHERE w.code = v.code;',
    '',
  ].join('\n');
}
