-- 0095: drop tottori-bousai's zero-level placeholder rows.
--
-- 鳥取県防災Web leaves some hourly dam lists incomplete — total=2 (朝鍋 +
-- 菅沢) instead of 6, about twice a day in September 2026. In those lists
-- 朝鍋's item, and at times a 菅沢 item copying it field for field, reads
-- 0 m / 0 千m³ with flag "0" (normal), while the same item prints a 最低水位
-- of 97.0 m (朝鍋) / 353.1 m (菅沢). Examples, still served verbatim:
--
--   /data/dam/list/2026-09-27-12-20.json  total 2: 朝鍋 0 m / 0 千m³ / 24 %,
--                                          菅沢 356.2 m / 429 千m³ (real)
--   /data/dam/list/2026-09-23-14-20.json  total 2: 朝鍋 and 菅沢 both
--                                          0 m / 0 千m³ / 24 % / 0.08 / 0.07
--
-- tottori-bousai (312) outranks tottori-dam (307) and cgr-mlit-dam (304), so
-- each placeholder was a plunge to an empty reservoir on the dam's chart.
-- ingest_tottori_bousai.ts now skips such items; this removes the stored ones.
--
-- Targeting: level exactly 0 under this source. All six dams it publishes sit
-- tens to hundreds of metres above sea level (最低水位 60.4–379.7 m), so no
-- real reading is 0. The whole row goes, not just level/volume: the rate and
-- flows in a copied item belong to another dam.
--
-- Prod dry-run (2026-09-27):
--   SELECT d.name, count(*) FROM observations o JOIN dams d ON d.id = o.dam_id
--   WHERE o.source_id = 'tottori-bousai' AND o.water_level_m = 0 GROUP BY 1;
--   → 朝鍋 256, 菅沢 17 (273 rows, 2026-06-05 … 2026-09-27)
--
-- Idempotent; a no-op on a fresh database.
DELETE FROM observations
WHERE source_id = 'tottori-bousai'
  AND water_level_m = 0;
